# Generated by Django 3.0.5 on 2025-06-02 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.CharField(auto_created='d228f330-d268-4cc4-9940-0aad392009aa', max_length=250),
        ),
    ]
