# Generated by Django 3.0.5 on 2025-06-02 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0002_auto_20250602_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.CharField(max_length=250),
        ),
    ]
