# Generated by Django 3.0.5 on 2025-06-02 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0004_paymentlogs_stripelogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlogs',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stripelogs',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
