# Generated by Django 3.0.5 on 2025-06-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0012_orders_transaction_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_id', models.IntegerField(unique=True)),
                ('error_message', models.CharField(max_length=1000)),
                ('error_type', models.CharField(max_length=1000)),
            ],
        ),
    ]
