# Generated by Django 3.0.5 on 2025-06-17 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0013_errormessages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='errormessages',
            name='error_type',
        ),
    ]
